baseurl: ""

url: https://dotrungkien.github.io

harmony:
  name: Momo's Blog
  description: Talk is cheap. Show me the code.
  basetheme: domomo
  author:
    name: Do Trung Kien
    email: trungkien162@gmail.com
    url: https://dotrungkien.github.io
  google_analytics_key: UA-106327334-1
  social:
    github: dotrungkien
    facebook: trungkien162
  show_disclaimer: true
show_drafts: false
future: true
unpublished: true
markdown:    kramdown
highlighter: rouge
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

permalink:        pretty

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

sass:
    sass_dir: assets/css/_sass
    style: :compressed
