baseurl: ''
url: https://dotrungkien.github.io

# Harmony theme configuration. Please change accordingly.
harmony:
  name: KienDT
  # Little description about your site
  description: Talk is cheap. Show me the code.
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author:
    name: Do Trung Kien
    email: trungkien162@gmail.com
    url: https://kiendt.me
  social:
    github: dotrungkien
    facebook: trungkien162
  google_analytics_key: UA-106327334-1

show_drafts: false
future: true
unpublished: true
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
# Permalinks
permalink: pretty

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
